In [8]:
import pandas as pd

In [11]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
pd_series = pd.Series(
    [1000,2000,3000,4000]
)

In [12]:
print(pd_series)

0    1000
1    2000
2    3000
3    4000
dtype: int64


In [13]:
print(type(pd_series))

<class 'pandas.core.series.Series'>


In [15]:
print(pd_series[2])

3000


In [17]:
#Series에 index를 추가하여 생성
#data의 개수와 index의 개수는 같게 생성
#그렇지 않으면 오류
pd_series2 = pd.Series(
    [5000,6000,6000,6500],
    index = ['아메리카노','카페라떼','카푸치노','카페모카']
)

In [19]:
print(pd_series2)

아메리카노    5000
카페라떼     6000
카푸치노     6000
카페모카     6500
dtype: int64


In [22]:
print(pd_series2['아메리카노'])
print(pd_series2[0])

5000
5000


C:\Users\Owner\AppData\Local\Temp\ipykernel_12512\1400210179.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(pd_series2[0])


In [24]:
#Series class -> 변수와 함수가 존재
#변수 중 데이터가 저장된 변수 : values
print('Series에서 데이터는' , pd_series2.values)

Series에서 데이터는 [5000 6000 6000 6500]


In [27]:
type(pd_series2.values) #행렬 형태

numpy.ndarray

In [29]:
#변수 중 index는 index라는 변수에 저장
print("Seres에서 index는",pd_series2.index)

Seres에서 index는 Index(['아메리카노', '카페라떼', '카푸치노', '카페모카'], dtype='object')


In [30]:
pd_series2['아메리카노'] = 5500

In [32]:
print(pd_series2.values)

[5500 6000 6000 6500]


In [41]:
pd_series2.index=['아메리카노','카페라떼','카푸치노','마끼아또']

In [44]:
print(pd_series2.index)
pd_series2

Index(['아메리카노', '카페라떼', '카푸치노', '마끼아또'], dtype='object')


아메리카노    5500
카페라떼     6000
카푸치노     6000
마끼아또     6500
dtype: int64

In [49]:
#2차원 데이터 : 데이터프레임
#데이터프레임은 1차원 데이터인 스리즈들의 묶음

data = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
pd_df = pd.DataFrame(data)
pd_df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [51]:
print(pd_df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [58]:
pd_df[1][2]=10

C:\Users\Owner\AppData\Local\Temp\ipykernel_12512\1066692769.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  pd_df[1][2]=10


In [60]:
pd_df

0   1  2
0  1   2  3
1  4   5  6
2  7  10  9

In [64]:
print(pd_df.values)
print(pd_df.index)
print(pd_df.columns)

[[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]
RangeIndex(start=0, stop=3, step=1)
RangeIndex(start=0, stop=3, step=1)


In [65]:
#DataFrame에서 columns를 변경해보자
pd_df.columns = ['A','B','C']

In [67]:
pd_df

A   B  C
0  1   2  3
1  4   5  6
2  7  10  9

In [76]:
#DataFrame에서 특정 column의 이름을 변경할 때
pd_df.rename(
    columns={'A':'a','C':'c'},
    index={1:10},
    inplace=True
    )


In [77]:
pd_df

a   B  c
0   1   2  3
10  4   5  6
2   7  10  9

In [78]:
df2 = pd_df

In [80]:
pd_df.rename(
    index = {
        0:100
    }, inplace=True
)

In [82]:
pd_df

a   B  c
100  1   2  3
10   4   5  6
2    7  10  9

In [99]:
#반복문을 이용해서 여러 개의 전역 변수를 생성하는 방법
# #전역 변수가 저장되어 있는 공간
# print(globals())

for i in range(5):
    # print(i)
    #반복 실행될 때 a + i가 더해진 변수명을 생성
    #a0, a1, a2, a3, a4
    print(f'a{i}')
    globals()[f'a{i}'] = i
    
    

a0
a1
a2
a3
a4


In [100]:
print(a1)

1


In [88]:
a=10

In [89]:
globals()['a']

10

In [91]:
globals()['b'] = 11

In [92]:
globals()['b']

11

In [102]:
#2차원 dict, list 혼합되어 있는 형태 -> 데이터 프레임
data = {
    'name': ['test1','test2','test3'],
    'age' : [20,30,40]
}

In [104]:
ddf = pd.DataFrame(data)
ddf

name  age
0  test1   20
1  test2   30
2  test3   40

In [110]:
print(data.keys())
print(data.values())

dict_keys(['name', 'age'])
dict_values([['test1', 'test2', 'test3'], [20, 30, 40]])


In [116]:
data2 = [
    {'name':'test1','age':20},
    {'kim':'test2','age':30}
]
df2 = pd.DataFrame(data2)

In [117]:
df2

name  age    kim
0  test1   20    NaN
1    NaN   30  test2

### 외부 데이터 파일 로드
- csv, tsv
    - pandas 안에 있는 read_csv(파일의 경로)
- json
    - pandas 안에 있는 read_json(파일의 경로)
- xml
    - pandas 안에 있는 read_xml(파일의 경로)

- 공통적으로 사용되는 매개변수
    - encoding 매개변수
        - 기본 값은 'UTF-8'
        - 데이터에 한글이 포함되어 있을 때 종종 에러 발생
            - 'CP949', 'EUC-KR'로 변경하면 에러 해결

- excel
    - read_excel(파일 경로)
    - encoding 매개변수 존재하지 않는다.
    - 한글이든 뭐든 상관 없다.